<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Documents.aspx.cs" Inherits="WebApplication1.Documents" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <main id="page-content" class="l-main" itemprop="mainContentOfPage">
	<section class="l-section wpb_row us_custom_4fb9e5a3 height_medium color_primary with_img"><div class="l-section-img" style="background-image: url(http://obdweb.co.za/JSEClear/wp-content/uploads/2022/11/Membership-Banner2.jpg);background-size: auto;" data-img-width="1920" data-img-height="390"></div><div class="l-section-h i-cf"><div class="g-cols vc_row via_grid cols_1 laptops-cols_inherit tablets-cols_inherit mobiles-cols_1 valign_middle type_default stacking_default"><div class="wpb_column vc_column_container"><div class="vc_column-inner"><div class="w-separator size_medium"></div><div class="wpb_text_column"><div class="wpb_wrapper"><h3><strong>Documents</strong></h3>
</div></div><div class="w-separator size_medium"></div></div></div></div></div></section><section class="l-section wpb_row height_medium"><div class="l-section-h i-cf"><div class="g-cols vc_row via_grid cols_1 laptops-cols_inherit tablets-cols_inherit mobiles-cols_1 valign_top type_default stacking_default"><div class="wpb_column vc_column_container"><div class="vc_column-inner"><div class="g-cols wpb_row via_grid cols_3 laptops-cols_inherit tablets-cols_inherit mobiles-cols_1 valign_top type_default stacking_default"><div class="wpb_column vc_column_container"><div class="vc_column-inner"><div class="wpb_text_column"><div class="wpb_wrapper"><h4>Membership</h4>
</div></div><div class="w-separator size_small"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">Fee Schedule</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">JSE Clear Membership Application Form</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">JSE Clear Rules</span></a></div></div></div><div class="wpb_column vc_column_container"><div class="vc_column-inner"><div class="wpb_text_column"><div class="wpb_wrapper"><h4>Risk Management</h4>
</div></div><div class="w-separator size_small"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">JSE Clear Initial Margin Policy</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">Derivative Market Technical Specifications</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">JSE Clear Margin Methodology</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">Portfolio VaR Implementation</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">Stress Testing Policy</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">Default Fund Policy</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">Investment Mandate</span></a></div></div></div><div class="wpb_column vc_column_container"><div class="vc_column-inner"><div class="wpb_text_column"><div class="wpb_wrapper"><h4>Collateral Management</h4>
</div></div><div class="w-separator size_small"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">Default Fund Policy</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">JSE Clear Collateral Policy</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">JSE Clear Collateral Risk Management Framework</span></a></div><div class="w-separator size_custom" style="height:10px"></div><div class="w-btn-wrapper width_full"><a class="w-btn us-btn-style_1" href="#"><span class="w-btn-label">JSE Clear Investment Mandate</span></a></div></div></div></div></div></div></div></div></section>
</main>

</asp:Content>
